# Sync repo to the Codeberg mirror
name: Mirror Sync

on:
  #push:
  #  branches: [ "master" ]
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: "0 */8 * * *"

jobs:
  codeberg:
    if: "github.repository == 'cuong-tran/komikku-extensions'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "git@codeberg.org:cuong-tran/komikku-extensions.git"
          ssh_private_key: ${{ secrets.CODEBERG_SSH }}
